language: ruby
dist: xenial

rvm:

2.6
2.7
3.0
3.1
3.2
cache:

bundler
script:

bundle exec rspec
jobs:
  include:
    - &job
      stage: test runtime dependency installation
      if: commit_message !~ /skip:test_dependencies/ AND env(SKIP_TEST_DEPENDENCIES) IS blank
      cache: false
      install:
      - gem build dpl.gemspec
      - gem install dpl-*.gem
      - nvm install 12.22.0
      - nvm use 12.22.0
      - node --version
      script:
      - .travis/test_install
      rvm: 2.6
    - <<: *job
      rvm: 2.7
    - <<: *job
      rvm: 3.0
    - <<: *job
      rvm: 3.1
    - <<: *job
      rvm: 3.2
    - <<: *job
   
     


